# Generated by Django 2.1.8 on 2020-06-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asd',
        ),
    ]
