# Generated by Django 2.1.8 on 2020-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0002_delete_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercollection',
            name='account_bank',
        ),
        migrations.RemoveField(
            model_name='customercollection',
            name='wechat',
        ),
        migrations.AddField(
            model_name='customercollection',
            name='account_method',
            field=models.CharField(max_length=32, null=True, verbose_name='收款方式'),
        ),
    ]
