# Generated by Django 2.1.8 on 2020-06-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0003_auto_20200602_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishpay',
            name='account_bank',
        ),
    ]
