# Generated by Django 2.1.8 on 2020-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0009_auto_20200603_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercollection',
            name='account_number',
            field=models.IntegerField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='number',
            field=models.IntegerField(max_length=16),
        ),
    ]
