# Generated by Django 2.1.8 on 2020-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0010_auto_20200603_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercollection',
            name='account_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
