# Generated by Django 2.1.8 on 2020-06-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0011_auto_20200603_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='saleman',
        ),
        migrations.AddField(
            model_name='pay',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klzg.Salesman', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='customercollection',
            name='name',
            field=models.CharField(max_length=32, verbose_name='联络人'),
        ),
    ]
