# Generated by Django 2.1.8 on 2020-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0012_auto_20200604_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='number',
            field=models.IntegerField(),
        ),
    ]
