# Generated by Django 2.1.8 on 2020-06-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0013_auto_20200604_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='customer',
        ),
        migrations.AddField(
            model_name='pay',
            name='customercol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klzg.CustomerCollection', verbose_name='客户联络人'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klzg.Salesman', verbose_name='业务负责人'),
        ),
    ]
