# Generated by Django 2.1.8 on 2020-06-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0014_auto_20200604_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='sales',
        ),
        migrations.AddField(
            model_name='commission',
            name='pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klzg.Pay', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='pay',
            name='number',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pay',
            name='customercol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klzg.CustomerCollection', verbose_name='客户联络人'),
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
