# Generated by Django 2.1.8 on 2020-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0016_auto_20200604_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
