# Generated by Django 2.1.8 on 2020-06-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0017_auto_20200604_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishpay',
            name='customer',
        ),
        migrations.AddField(
            model_name='finishpay',
            name='customercol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klzg.CustomerCollection', verbose_name='客户联络人'),
        ),
    ]
