# Generated by Django 2.1.8 on 2020-06-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0018_auto_20200604_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishpay',
            name='customercol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klzg.CustomerCollection', verbose_name='客户联络人'),
        ),
    ]
