# Generated by Django 2.1.8 on 2020-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0020_auto_20200604_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True, verbose_name='月销量')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
    ]
