# Generated by Django 2.1.8 on 2020-06-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0021_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='number',
        ),
        migrations.AddField(
            model_name='commission',
            name='sales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klzg.Sales', verbose_name='销量'),
        ),
    ]
