# Generated by Django 2.1.8 on 2020-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0022_auto_20200604_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='remark',
            field=models.CharField(max_length=32, null=True, verbose_name='备注'),
        ),
    ]
