# Generated by Django 2.1.8 on 2020-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0023_commission_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='remark',
            field=models.CharField(default='未付', max_length=32, verbose_name='备注'),
        ),
    ]
