# Generated by Django 2.1.8 on 2020-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0024_auto_20200608_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salesman', models.CharField(max_length=32, verbose_name='业务员')),
                ('customer', models.CharField(max_length=64, verbose_name='客户')),
                ('customercol', models.CharField(max_length=32, verbose_name='联络人')),
                ('number', models.IntegerField(verbose_name='销量')),
                ('total', models.IntegerField(verbose_name='金额')),
            ],
        ),
    ]
