# Generated by Django 2.1.8 on 2020-06-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0025_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已付'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klzg.Sales', verbose_name='销量'),
        ),
    ]
