# Generated by Django 2.1.8 on 2020-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0026_auto_20200611_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='money',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='已付'),
        ),
    ]
