# Generated by Django 2.1.8 on 2020-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0027_auto_20200611_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='remark',
        ),
    ]
