# Generated by Django 2.1.8 on 2020-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0028_remove_commission_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='已付'),
        ),
    ]
