# Generated by Django 2.1.8 on 2020-06-11 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0029_auto_20200611_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='total',
        ),
        migrations.AddField(
            model_name='history',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 11, 16, 56, 27, 257523), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='时间'),
        ),
    ]
