# Generated by Django 2.1.8 on 2020-06-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0030_auto_20200611_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
