# Generated by Django 2.1.8 on 2020-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0031_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='end_time',
            field=models.DateTimeField(default='9999-12-30 01:01:01', verbose_name='结束时间'),
        ),
    ]
