# Generated by Django 2.1.8 on 2020-06-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klzg', '0032_auto_20200616_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klzg.Customer', verbose_name='所属客户'),
        ),
    ]
