# Generated by Django 2.1.8 on 2020-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(null=True, upload_to='avatars/')),
            ],
        ),
    ]
