# Generated by Django 2.1.8 on 2020-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20200615_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='avatar',
            new_name='file_name',
        ),
    ]
